language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-repair-recipe' ]; then cd .. && eval "mv $currentfolder generator-repair-recipe" && cd generator-repair-recipe; fi
